### ISSUE TITLE
cant upload - invalid_auth

### ISSUE THREAD

**Issue by mrtaco00** [Fauntleroy/neutral-face-emoji-tools#11]
when i drag and drop, i get an error: invalid auth.  thought it might be because i was logged into multiple workspaces, but logged out of all of them and then just logged into one, but still no joy.  any ideas?

{"ok":false,"error":"invalid_auth"}

**Comment by akx** [comment]
#10 fixes this.

**Comment by mrtaco00** [comment]
excellent!  thanks for the tip - worked like a charm
