### ISSUE TITLE
User tokens have moved

### ISSUE THREAD

**Issue by jackellenberger** [Fauntleroy/neutral-face-emoji-tools#12]
Looks like a recent Slack update moved the api_token from being in a big string / array of strings / whatever it was to a proper json object, still called `boot_data`.

So instead of doing [a regex search](https://github.com/Fauntleroy/neutral-face-emoji-tools/blob/master/src/get-slack-api-data.js#L13) we should be able to just access it as `window.boot_data.api_token` :nice:

**Comment by akx** [comment]
#10 fixes this.
