### ISSUE TITLE
UI appears on one workspace, not another even tho Chrome extension is active

### ISSUE THREAD

**Issue by CindyHavens** [Fauntleroy/neutral-face-emoji-tools#20]
Strangest thing - I'm a primary owner on a couple of slack sites.  I can open a chrome browser tab on one workspace, and the Neutral Face Emoji Bulk Loader UI appears on the customize page.  On another workspace, the chrome extension appears active, but the bulk upload UI does not appear.  

Same behavior on different workstations, both running Chrome 81.0.4044.92.  Ideas?
![image](https://user-images.githubusercontent.com/63926746/79668842-406cf900-817d-11ea-9d18-9194153193eb.png)

**Comment by Fauntleroy** [comment]
Looks like this is actually this issue: https://github.com/Fauntleroy/neutral-face-emoji-tools/issues/7

Closing for now in lieu of the other issue.
