### ISSUE TITLE
I think it's broken due to slack UI upgrade

### ISSUE THREAD

**Issue by coderbec** [Fauntleroy/neutral-face-emoji-tools#24]
Not working in chrome for me anymore..

**Comment by notjoelshapiro** [comment]
+1, I'm not able to get this to work in Chrome or Firefox. Hugely disappointing.

**Comment by ryanmaynard** [comment]
I'll venmo $200 to anyone that wants to submit a PR to get it working with the new UI in the next week. Wish bug bounties were more common. This is a great repo and tool and @Fauntleroy deserves more cred/$$ for it.

**Comment by coderbec** [comment]
Hey just checking in here because I actually did manage to get this working and I'm pretty sure the bug isn't the new UI. It's because I was trying it on a brand new slack channel -one you have manually uploaded more than one emoji yourself it appears to work fine.

**Comment by Fauntleroy** [comment]
@coderbec Thanks for raising this issue! I'm a bit confused though—the Slack admin interface hasn't changed for me:

<img width="1005" alt="image" src="https://user-images.githubusercontent.com/507047/109870484-01be2100-7c1f-11eb-9402-53e1a23a60a4.png">

Does the Slack admin look different to you? Is this happening at "orgname.slack.com/customize/emoji"?

**Comment by Fauntleroy** [comment]
On further investigation it looks like this is the root cause of the issue? https://github.com/Fauntleroy/neutral-face-emoji-tools/issues/7

**Comment by ryanmaynard** [comment]
Hi all. I deleted my comment, but should have left and merely edited. 
I found that "It's because I was trying it on a brand new slack channel -one you have manually uploaded more than one emoji yourself it appears to work fine." was true before this comment was posted, so I deleted my original comment, assuming it was my own ignorance, and not a bug.

**Comment by coderbec** [comment]
yes, just to confirm 100% what I mean, I had one slack channel I hadn't customised yet so I got screen shots. On a new channel with no emojis yet the element you look for to insert your div isn't there yet, so it doesn't work: 

![Screen Shot 2021-03-04 at 12 03 44 pm](https://user-images.githubusercontent.com/9004716/109894665-00a1f800-7ce2-11eb-8a94-28a155f1a6aa.png)

After I uploaded one parrot emoji manually the extension worked again: 
![Screen Shot 2021-03-04 at 12 04 58 pm](https://user-images.githubusercontent.com/9004716/109894710-16afb880-7ce2-11eb-981a-1f8896482865.png)

Probably too hard to fix this conditionally, so you could just put a warning on the extension page about it and save yourself the 1 star reviews?

Anyway, thanks for doing this extension and enabling our party parrot shenanigans.
