### ISSUE TITLE
Extension removed from chrome webstore?

### ISSUE THREAD

**Issue by ragebiswas** [Fauntleroy/neutral-face-emoji-tools#28]
Hey @Fauntleroy , was this extension removed or is it just me? Chrome throws a 404 for https://chrome.google.com/webstore/detail/neutral-face-emoji-tools/anchoacphlfbdomdlomnbbfhcmcdmjej?hl=en

If it's just me, please ignore and apologies!

**Comment by jhollowe** [comment]
That link works for me

**Comment by Fauntleroy** [comment]
@ragebiswas The extension was removed briefly due to a change in how extensions are validated. It's now working for me (showing version 3.2.0)
